name: Strapi Trigger
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          echo "Trigger run for version ${{ github.event.inputs.version }} at {{ github.ref_name }}"