name: Strapi Trigger
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: ''

concurrency: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          echo "Trigger run for version ${{ github.event.inputs.version }} at ${{ github.ref_name }}"

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_AUTOMATION_TOKEN }}
          publish_dir: ./build